- name: Gather facts from standalone ESXi server having datacenter as RVX2-MMC-DC
  vmware_guest_facts:
    hostname: 10.234.122.95
    username: administrator@vsphere.local
    password: Vc3m0l@b
    datacenter: RVX2-MMC-DC
    uuid: 420fba4c-940f-9ed7-4fea-3ef52e1253bd
    validate_certs: no
  delegate_to: localhost
  register: facts	
